### ISSUE TITLE
Freeze when clicking icon in v1.3.0 (Insiders) for mac

### ISSUE THREAD

**Issue by huyz** [swar8080/obsidian-plugin-update-tracker#60] opened 2023-05-16 10:42 UTC
At least two of us are experiencing an issue whenever we click on this plugin's icon in the bottom toolbar: freeze of the UI. And then we have to restart Obsidian.

Now, I've also experienced other UI freezes without clicking on that icon, so I figured that v1.3.0 is just too unstable. So I downgraded to v1.2.8 and everything went back to normal.

But I figure I'd file an issue in case there's some way in which this plugin can be updated to adapt.

**Comment by swar8080** [comment] 2023-05-16 11:41
Thanks for the heads up

**Comment by huyz** [comment] 2023-05-24 02:32
v1.3.3 was released to the stable channel.  And the freeze-up still happens.

**Comment by swar8080** [comment] 2023-05-24 10:38
Hmm I can't reproduce this on mac 1.3.3 so maybe there's a specific plugin or setting causing the problem. @huyz when the freeze happens, do you see any errors in the Developer Tools console?: 
<img width="1512" alt="image" src="https://github.com/swar8080/obsidian-plugin-update-tracker/assets/17691679/52dabe95-5dbc-4715-abe9-d885ae271dd1">

Also, if you want to include the output of obsidian's _Help_ > _Debug Info_  then we might see a pattern of what plugins  people have installed when freezing happens

**Comment by yarub123** [comment] 2023-06-20 05:50
The freezing issue has come up for me too. I thought it would go away... but here I am 3 days later still experiencing it... and I'm not on insiders. Just regular obsidian for regular average human beings.

**Comment by swar8080** [comment] 2023-06-20 22:33
Hey @yarub123, do you see any errors in the Developer Tools console _(View > Toggle Developer Tools > Console_)? I'm not having this problem on my mac

Also, if you include the output of _Help > Debug Info_ then maybe we can identify another plugin that this plugin doesn't work with

**Comment by yarub123** [comment] 2023-06-26 06:52
@swar8080 Real quick, just wanted to pass one thing by you. Do you think this could be related? Also I used a sandbox vault issue is cleared. So it's clearly one of my plugins. I just have so many, so I will just test them one by one haha. It's def a plugin issue. 

Anyways what's this? I always see it in the console: Thanks for your reply btw, much appreciated 🙏
<img width="539" alt="image" src="https://github.com/swar8080/obsidian-plugin-update-tracker/assets/84487964/2cfdc903-5444-4b99-9c0e-b43660f63f88">

**Comment by swar8080** [comment] 2023-06-26 22:38
Thanks for the console output and testing which plugin is causing this. The console message is unrelated though

If you have lots of plugins you could post the list from obsidian's _Help > Debug Info_ to see which ones @huyz also has installed

**Comment by workflowsguy** [comment] 2023-07-22 09:52
I have the same problem. To reproduce:

- Open Developer Console in Obsidian
- Click the Plugins icon

-> 
- Obsidian main window (where a note is displayed) locks up.
- Developer Console stays responsive, but there are no additional lines in the output.

macOS 13.4.1 (c)

## Obsidian Debug info
```
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 22.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Spectrum v0.0.0
	Snippets enabled: 0
	Restricted mode: off
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 61
	Plugins enabled: 50
		1: Note Refactor v1.7.1
		2: Link indexer v1.0.0
		3: Search++ v0.0.1
		4: Workbench v1.6.1
		5: Dangling links v0.3.0
		6: Copy button for code blocks (fixed version manifest) v0.2.1
		7: macOS Keyboard Navigation v1.1.2
		8: Automatically reveal active file v1.0.2
		9: Quick Switcher++ v3.3.2
		10: Markdown prettifier v0.1.3
		11: Hotkeys++ v0.2.7
		12: Calendar v1.5.10
		13: Cycle through Panes v1.2.1
		14: Jump to link v0.4.4
		15: Add links to current note v0.0.9
		16: Advanced Tables v0.18.1
		17: Find orphaned files and broken links v1.9.0
		18: Paste URL into selection v1.7.0
		19: Recent Files v1.3.6
		20: Kanban v1.5.3
		21: Dataview v0.5.56
		22: Icons v0.3.0
		23: Emoji Toolbar v0.4.1
		24: Natural Language Dates v0.6.1
		25: Pluck v1.0.1
		26: Hotkey Helper v0.3.18
		27: Buttons v0.4.19
		28: Convert url to preview (iframe) v0.5.0
		29: Editor Syntax Highlight v0.1.3
		30: Hotkeys for templates v1.4.3
		31: Minimal Theme Settings v6.3.1
		32: Tabout v1.0.0
		33: Pikt v0.2.0
		34: Excalidraw v1.9.3
		35: File Tree Alternative Plugin v2.3.4
		36: Cursor Location v0.3.0
		37: MetaEdit v1.8.0
		38: Regex Find/Replace v1.2.0
		39: Breadcrumbs v3.6.4
		40: Native Scrollbars v1.0.1
		41: Update time on edit v1.1.2
		42: Templater v1.16.0
		43: Vault Changelog v0.1.0
		44: Hover Editor v0.11.12
		45: Emoji Shortcodes v2.2.0
		46: Better CodeBlock v1.0.8
		47: Outliner v4.7.1
		48: Colorful Note Borders v0.2.4
		49: Colorful Tag v1.3.2
		50: Plugin Update Tracker v1.5.1
```

**Comment by swar8080** [comment] 2023-07-23 22:19
`Cursor Location v0.3.0` seems to be what's causing this. Thanks for posting your plugins @workflowsguy 

Someone already reported the issue to that plugin's author and has a fix waiting to be merged: https://github.com/spslater/obsidian-cursor-location-plugin/pull/22. I tested their fix and it solves the problem. The author mentioned they'll merge it soon when they're back from vacation, so probably this'll be fixed soon

**Comment by workflowsguy** [comment] 2023-07-24 07:43
@swar8080,

I can also confirm that after disabling `Cursor Location v0.3.0`, `Update Tracker` now works.

Great to hear that the cause was found and is being addressed so that I can use both of those very useful plugins together.

Thanks!

**Closed** 2023-07-24 15:01 UTC
